In [1]:
import numpy as np

## Datatypes and Attributes

In [2]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [6]:
a2 = np.array([[1,2,3],
              [4,5,6.5]])
a3 = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ],
    [
        [13,14,15],
        [16,17,18]
    ]]
)

In [11]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(3, 2, 3)

In [10]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [12]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [13]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [14]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [15]:
# Create a Dataframe from a Numpy array
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.5

## Creating Numpy arrays

In [16]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [17]:
ones = np.ones((2,3),dtype=int)


In [18]:
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [19]:
type(ones)

numpy.ndarray

In [20]:
zeros = np.zeros((3,2))
zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [21]:
range_array = np.arange(2,11,2)
range_array

array([ 2,  4,  6,  8, 10])

In [28]:
random_array = np.random.randint(0,10,(4,3,2))
random_array

array([[[9, 3],
        [4, 3],
        [2, 0]],

       [[7, 0],
        [5, 0],
        [0, 8]],

       [[1, 2],
        [4, 0],
        [3, 8]],

       [[2, 6],
        [6, 4],
        [5, 7]]], dtype=int32)

In [29]:
random_array_2 = np.random.random((4,3))
random_array_2



array([[0.56127164, 0.60330514, 0.78456236],
       [0.94960834, 0.54989052, 0.55916202],
       [0.97250596, 0.12794305, 0.92435372],
       [0.20491854, 0.04367758, 0.44271681]])

In [30]:
random_array_2.shape

(4, 3)

In [33]:

random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.88209998, 0.79319881, 0.01979613],
       [0.52635071, 0.91001859, 0.83073213],
       [0.01407007, 0.74910432, 0.65988228],
       [0.59142167, 0.27268258, 0.55755025],
       [0.89264062, 0.08575864, 0.74257452]])

In [34]:
# Pseudo-random numbers
# np.rendom.seed()

In [44]:
np.random.seed(1)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 8, 9],
       [5, 0, 0],
       [1, 7, 6],
       [9, 2, 4],
       [5, 2, 4]], dtype=int32)

In [45]:
np.random.seed(1)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 8, 9],
       [5, 0, 0],
       [1, 7, 6],
       [9, 2, 4],
       [5, 2, 4]], dtype=int32)

In [49]:
np.random.seed(6)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[9, 3, 4],
       [0, 9, 1],
       [9, 1, 4],
       [1, 8, 2],
       [4, 2, 5]], dtype=int32)